/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultsRouteImport } from './routes/vaults'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as EarnRouteImport } from './routes/earn'
import { Route as AgentPearRouteImport } from './routes/agent-pear'
import { Route as IndexRouteImport } from './routes/index'

const VaultsRoute = VaultsRouteImport.update({
  id: '/vaults',
  path: '/vaults',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnRoute = EarnRouteImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentPearRoute = AgentPearRouteImport.update({
  id: '/agent-pear',
  path: '/agent-pear',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-pear': typeof AgentPearRoute
  '/earn': typeof EarnRoute
  '/markets': typeof MarketsRoute
  '/portfolio': typeof PortfolioRoute
  '/trade': typeof TradeRoute
  '/vaults': typeof VaultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-pear': typeof AgentPearRoute
  '/earn': typeof EarnRoute
  '/markets': typeof MarketsRoute
  '/portfolio': typeof PortfolioRoute
  '/trade': typeof TradeRoute
  '/vaults': typeof VaultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-pear': typeof AgentPearRoute
  '/earn': typeof EarnRoute
  '/markets': typeof MarketsRoute
  '/portfolio': typeof PortfolioRoute
  '/trade': typeof TradeRoute
  '/vaults': typeof VaultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-pear'
    | '/earn'
    | '/markets'
    | '/portfolio'
    | '/trade'
    | '/vaults'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-pear'
    | '/earn'
    | '/markets'
    | '/portfolio'
    | '/trade'
    | '/vaults'
  id:
    | '__root__'
    | '/'
    | '/agent-pear'
    | '/earn'
    | '/markets'
    | '/portfolio'
    | '/trade'
    | '/vaults'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentPearRoute: typeof AgentPearRoute
  EarnRoute: typeof EarnRoute
  MarketsRoute: typeof MarketsRoute
  PortfolioRoute: typeof PortfolioRoute
  TradeRoute: typeof TradeRoute
  VaultsRoute: typeof VaultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vaults': {
      id: '/vaults'
      path: '/vaults'
      fullPath: '/vaults'
      preLoaderRoute: typeof VaultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earn': {
      id: '/earn'
      path: '/earn'
      fullPath: '/earn'
      preLoaderRoute: typeof EarnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-pear': {
      id: '/agent-pear'
      path: '/agent-pear'
      fullPath: '/agent-pear'
      preLoaderRoute: typeof AgentPearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentPearRoute: AgentPearRoute,
  EarnRoute: EarnRoute,
  MarketsRoute: MarketsRoute,
  PortfolioRoute: PortfolioRoute,
  TradeRoute: TradeRoute,
  VaultsRoute: VaultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
